service: default
runtime: nodejs20
instance_class: F1

handlers:
  - url: /
    secure: always
    redirect_http_response_code: 301
    static_files: public/index.html
    upload: public/index.html
    http_headers:
      Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'
      X-Content-Type-Options: nosniff
      X-XSS-Protection: 1; mode=block
      X-FRAME-OPTIONS: 'sameorigin'
      Referrer-Policy: 'strict-origin-when-cross-origin'
  - url: /(.*)/
    secure: always
    redirect_http_response_code: 301
    static_files: public/\1/index.html
    upload: public/(.*)/index.html
    http_headers:
      Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'
      X-Content-Type-Options: nosniff
      X-XSS-Protection: 1; mode=block
      X-FRAME-OPTIONS: 'sameorigin'
      Referrer-Policy: 'strict-origin-when-cross-origin'
  - url: /(.*)
    secure: always
    redirect_http_response_code: 301
    static_files: public/\1
    upload: public/(.*)
    http_headers:
      Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'
      X-Content-Type-Options: nosniff
      X-XSS-Protection: 1; mode=block
      X-FRAME-OPTIONS: 'sameorigin'
      Referrer-Policy: 'strict-origin-when-cross-origin'

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.8
