/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/


<script>
  export let id = undefined;
  export let style = undefined;
  export let size = "3rem";
</script>

<svg width={size} height={size} fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M42.5 35.5a1.5 1.5 0 01-1.1-.5L24 16.21 6.6 35a1.5 1.5 0 11-2.2-2l18.46-20a1.51 1.51 0 011.14-.5 1.49 1.49 0 011.1.48L43.6 33a1.5 1.5 0 01-.08 2.12 1.48 1.48 0 01-1.02.38z"/></svg>