/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/


<script>
  export let id = undefined;
  export let style = undefined;
  export let size = "3rem";
</script>

<svg width={size} height={size} fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M42.15 4H25.5a1.5 1.5 0 000 3h13.38L17.44 28.44a1.49 1.49 0 000 2.12 1.5 1.5 0 002.12 0L41 9.12V22.5a1.5 1.5 0 003 0V5.85A1.85 1.85 0 0042.15 4z"/><path d="M37 41H7V11h9V8H6a2 2 0 00-2 2v32a2 2 0 002 2h32a2 2 0 002-2V32h-3z"/></svg>