/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/


<script>
  export let id = undefined;
  export let style = undefined;
  export let size = "3rem";
</script>

<svg width={size} height={size} fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><circle cx="14" cy="24" r="2.5"/><circle cx="24" cy="24" r="2.5"/><circle cx="34" cy="24" r="2.5"/></svg>