/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/


<script>
  export let id = undefined;
  export let style = undefined;
  export let size = "1.5rem";
</script>

<svg width={size} height={size} fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9.5 13h-6A1.5 1.5 0 002 14.5v6A1.5 1.5 0 003.5 22h6a1.5 1.5 0 001.5-1.5v-6A1.5 1.5 0 009.5 13zM9 20H4v-5h5zM20.5 13h-6a1.5 1.5 0 00-1.5 1.5v6a1.5 1.5 0 001.5 1.5h6a1.5 1.5 0 001.5-1.5v-6a1.5 1.5 0 00-1.5-1.5zm-.5 7h-5v-5h5zM9.5 2h-6A1.5 1.5 0 002 3.5v6A1.5 1.5 0 003.5 11h6A1.5 1.5 0 0011 9.5v-6A1.5 1.5 0 009.5 2zM9 9H4V4h5zM20.5 2h-6A1.5 1.5 0 0013 3.5v6a1.5 1.5 0 001.5 1.5h6A1.5 1.5 0 0022 9.5v-6A1.5 1.5 0 0020.5 2zM20 9h-5V4h5z"/></svg>