/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/


<script>
  export let id = undefined;
  export let style = undefined;
  export let size = "3rem";
</script>

<svg width={size} height={size} fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M7.5 16h33a1.5 1.5 0 000-3h-33a1.5 1.5 0 000 3zM40.5 32h-33a1.5 1.5 0 000 3h33a1.5 1.5 0 000-3zM40.5 22.5h-33a1.5 1.5 0 000 3h33a1.5 1.5 0 000-3z"/></svg>