/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/


<script>
  export let id = undefined;
  export let style = undefined;
  export let size = "3rem";
</script>

<svg width={size} height={size} fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M24 8.34l4.15 8.84.68 1.45 1.58.24L40 20.34l-7 7.21-1.05 1.08.24 1.49 1.63 10-8.33-4.6L24 34.7l-1.45.8-8.33 4.6 1.63-10 .24-1.49L15 27.55l-7-7.21 9.58-1.47 1.58-.24.68-1.45L24 8.34m0-4.26a2 2 0 00-1.87 1.19l-5 10.64-11.37 1.74a2.06 2.06 0 00-1.17 3.48l8.3 8.51L11 41.52a2.08 2.08 0 002 2.4 2 2 0 001-.26l10-5.53 10 5.53a2 2 0 001 .26 2.08 2.08 0 002-2.4l-1.89-11.88 8.3-8.51a2.06 2.06 0 00-1.17-3.48l-11.37-1.74-5-10.64A2 2 0 0024 4.08z"/></svg>