/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/


<script>
  export let id = undefined;
  export let style = undefined;
  export let size = "4rem";
</script>

<svg width={size} height={size} fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><path d="M32 5.25l-8.35 17.78L5 25.88l13.5 13.83-3.19 19.54L32 50.03l.04.02V5.34L32 5.25z"/></svg>