/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/


<script>
  export let id = undefined;
  export let style = undefined;
  export let size = "1rem";
</script>

<svg width={size} height={size} fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M8 11.95V2L6.15 5.95 2 6.58l3 3.08L4.29 14 8 11.95z"/><path d="M8 11.95V2L6.15 5.95 2 6.58l3 3.08L4.29 14 8 11.95z"/></svg>