name: ðŸž Bug Report
description: Report a bug
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Hi there! :wave: :smiley:
        Thanks for taking the time to fill out this bug report!

        > To expedite issue processing please search open and closed issues before submitting a new one.
  - type: dropdown
    id: package-concerned
    attributes:
      label: I am opening an issue for
      options:
        - Documentation
        - Design Tokens
        - Component
        - Tools (PostCSS, Stylelint, ...)
        - Styles (CSS, SCSS, ...)
        - Icon set
        - Figma
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: Which version of the package is affected?
      placeholder: e.g., @mozaic-ds/styles@1.41.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: github-repository
    attributes:
      label: GitHub repository
      description: To better help you, please indicate the URL of your GitHub repo.
      placeholder: e.g., https://github.com/adeo/mozaic-design-system
  - type: input
    id: mockups
    attributes:
      label: Mock-up(s)
      description: Please, indicate the URL of your Figma mock-up to give us more context.
      placeholder: e.g., https://www.figma.com/file/b09kkFmjlH6RnLEDF2vppS/%5BBA%5D-Button-%F0%9F%9F%A2?node-id=0%3A1
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us, what's happening?
      placeholder: |
        Tell us what you see.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: textarea
    id: what-expected
    attributes:
      label: What is expected?
      description: Tell us, what did you expect to happen?
      placeholder: Describe the expected outcome.
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: textarea
    id: code
    attributes:
      label: Code example
      description: Copy here the concerned code or an example of code.
      render: HTML
  - type: checkboxes
    id: regression
    attributes:
      label: Is this a regression?
      description: Did this behavior use to work in the previous version?
      options:
        - label: 'Yes'
        - label: 'No'
        - label: "I don't know"
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional comments
      description: Add any other comments about the problem here.
      placeholder: |
        Is this a browser specific issue? If so, please specify the browser and version.
        Do you have specific setup for sketch, plugins, etc.
        Do any of these matter: operating system, IDE, package manager, HTTP server, ...?
  - type: markdown
    attributes:
      value: |
        # :raising_hand: Have you thought making a contribution?
        **Mozaic** is an inner source project, **open to free contribution**.
        The contribution is one of the ways to get quickly a fix to your issue.
        To learn more, please read our [contribution guidelines](https://github.com/adeo/mozaic-vue/blob/master/CONTRIBUTING.md).
