name: 🚀 Feature request
description: Suggest an idea for this project
labels: [':rocket: feat']
body:
  - type: markdown
    attributes:
      value: |
        Hi there! :wave: :smiley:
        Thank you for taking the time to fill out this feature request and helping us expand/improve the Design System!

        > To expedite issue processing please search open and closed issues before submitting a new one.
  - type: dropdown
    id: about
    attributes:
      label: I want to propose an evolution/improvement on
      options:
        - Documentation
        - Design Tokens
        - Component
        - Tools (PostCSS, Stylelint, ...)
        - Styles (CSS, SCSS, ...)
        - Icon set
        - Figma
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of the issue or what you are missing.
    validations:
      required: true

  - type: textarea
    id: describe-solution
    attributes:
      label: Describe the solution you would like
      placeholder: If you have a solution in mind, please describe it.
  - type: textarea
    id: describe-alternatives
    attributes:
      label: Describe the alternatives you considered
      placeholder: Have you considered any alternative solutions or workarounds?
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional comments
      placeholder: |
        Add any other comments or anything else relevant about your request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
