const { parse } = require("svg-parser")
const { createComponentName, convertPxToRem } = require("../utils/tools")

const jsonIconObject = ({ fileName, data }) => {
  const parsedFileName = createComponentName(fileName)
  const sizePx = fileName.replace(".svg", "").split("_").pop()
  const size = convertPxToRem(sizePx.replace("px", ""))
  const parsedSVG = parse(data)
  const viewBox = parsedSVG.children[0].properties.viewBox
  const content = parsedSVG.children[0].children

  if (!size || !viewBox || !content || content.length === 0) {
    console.error(
      `✗ ERROR : there was a problem building ${fileName} for vueJS`
    )

    return null
  }

  return `"${parsedFileName}": {
    "viewBox": "${viewBox}",
    "size": "${size}",
    "paths": [
      ${content.map(
        (elem) => `{
          "tagName": "${elem.tagName}",
          "attrs": ${JSON.stringify(elem.properties)}
        }`
      )}
    ]    
  }`
}

const jsonIconsIndex = (iconList) => `
{
  "__comment__": "DON'T EDIT THIS FILE - It was auto-generated by 'iconCompiler' script",
  ${iconList.map(jsonIconObject).join(",")}
}
`

module.exports = jsonIconsIndex
