import * as tokens from '../../tokens/dist/_design_tokens.module.js'

export default {
  'primary-01': {
    '900': {
      RGBval: tokens.pColorPrimary01900,
      scss: '$p-color-primary-01-900',
      js: 'pColorPrimary01900',
      json: 'p-color-primary-01-900',
      xml: 'P_COLOR_PRIMARY_01_900',
    },
    '800': {
      RGBval: tokens.pColorPrimary01800,
      scss: '$p-color-primary-01-800',
      js: 'pColorPrimary01800',
      json: 'p-color-primary-01-800',
      xml: 'P_COLOR_PRIMARY_01_800',
    },
    '700': {
      RGBval: tokens.pColorPrimary01700,
      scss: '$p-color-primary-01-700',
      js: 'pColorPrimary01700',
      json: 'p-color-primary-01-700',
      xml: 'P_COLOR_PRIMARY_01_700',
    },
    '600': {
      RGBval: tokens.pColorPrimary01600,
      scss: '$p-color-primary-01-600',
      js: 'pColorPrimary01600',
      json: 'p-color-primary-01-600',
      xml: 'P_COLOR_PRIMARY_01_600',
    },
    '500': {
      RGBval: tokens.pColorPrimary01500,
      scss: '$p-color-primary-01-500',
      js: 'pColorPrimary01500',
      json: 'p-color-primary-01-500',
      xml: 'P_COLOR_PRIMARY_01_500',
    },
    '400': {
      RGBval: tokens.pColorPrimary01400,
      scss: '$p-color-primary-01-400',
      js: 'pColorPrimary01400',
      json: 'p-color-primary-01-400',
      xml: 'P_COLOR_PRIMARY_01_400',
    },
    '300': {
      RGBval: tokens.pColorPrimary01300,
      scss: '$p-color-primary-01-300',
      js: 'pColorPrimary01300',
      json: 'p-color-primary-01-300',
      xml: 'P_COLOR_PRIMARY_01_300',
    },
    '200': {
      RGBval: tokens.pColorPrimary01200,
      scss: '$p-color-primary-01-200',
      js: 'pColorPrimary01200',
      json: 'p-color-primary-01-200',
      xml: 'P_COLOR_PRIMARY_01_200',
    },
    '100': {
      RGBval: tokens.pColorPrimary01100,
      scss: '$p-color-primary-01-100',
      js: 'pColorPrimary01100',
      json: 'p-color-primary-01-100',
      xml: 'P_COLOR_PRIMARY_01_100',
    },
  },
  'primary-02': {
    '900': {
      RGBval: tokens.pColorPrimary02900,
      scss: '$p-color-primary-02-900',
      js: 'pColorPrimary02900',
      json: 'p-color-primary-02-900',
      xml: 'P_COLOR_PRIMARY_02_900',
    },
    '800': {
      RGBval: tokens.pColorPrimary02800,
      scss: '$p-color-primary-02-800',
      js: 'pColorPrimary02800',
      json: 'p-color-primary-02-800',
      xml: 'P_COLOR_PRIMARY_02_800',
    },
    '700': {
      RGBval: tokens.pColorPrimary02700,
      scss: '$p-color-primary-02-700',
      js: 'pColorPrimary02700',
      json: 'p-color-primary-02-700',
      xml: 'P_COLOR_PRIMARY_02_700',
    },
    '600': {
      RGBval: tokens.pColorPrimary02600,
      scss: '$p-color-primary-02-600',
      js: 'pColorPrimary02600',
      json: 'p-color-primary-02-600',
      xml: 'P_COLOR_PRIMARY_02_600',
    },
    '500': {
      RGBval: tokens.pColorPrimary02500,
      scss: '$p-color-primary-02-500',
      js: 'pColorPrimary02500',
      json: 'p-color-primary-02-500',
      xml: 'P_COLOR_PRIMARY_02_500',
    },
    '400': {
      RGBval: tokens.pColorPrimary02400,
      scss: '$p-color-primary-02-400',
      js: 'pColorPrimary02400',
      json: 'p-color-primary-02-400',
      xml: 'P_COLOR_PRIMARY_02_400',
    },
    '300': {
      RGBval: tokens.pColorPrimary02300,
      scss: '$p-color-primary-02-300',
      js: 'pColorPrimary02300',
      json: 'p-color-primary-02-300',
      xml: 'P_COLOR_PRIMARY_02_300',
    },
    '200': {
      RGBval: tokens.pColorPrimary02200,
      scss: '$p-color-primary-02-200',
      js: 'pColorPrimary02200',
      json: 'p-color-primary-02-200',
      xml: 'P_COLOR_PRIMARY_02_200',
    },
    '100': {
      RGBval: tokens.pColorPrimary02100,
      scss: '$p-color-primary-02-100',
      js: 'pColorPrimary02100',
      json: 'p-color-primary-02-100',
      xml: 'P_COLOR_PRIMARY_02_100',
    },
  },
  grey: {
    '999': {
      RGBval: tokens.pColorGrey999,
      scss: '$p-color-grey-999',
      js: 'pColorGrey999',
      json: 'p-color-grey-999',
      xml: 'P_COLOR_GREY_999',
    },
    '900': {
      RGBval: tokens.pColorGrey900,
      scss: '$p-color-grey-900',
      js: 'pColorGrey900',
      json: 'p-color-grey-900',
      xml: 'P_COLOR_GREY_900',
    },
    '800': {
      RGBval: tokens.pColorGrey800,
      scss: '$p-color-grey-800',
      js: 'pColorGrey800',
      json: 'p-color-grey-800',
      xml: 'P_COLOR_GREY_800',
    },
    '700': {
      RGBval: tokens.pColorGrey700,
      scss: '$p-color-grey-700',
      js: 'pColorGrey700',
      json: 'p-color-grey-700',
      xml: 'P_COLOR_GREY_700',
    },
    '600': {
      RGBval: tokens.pColorGrey600,
      scss: '$p-color-grey-600',
      js: 'pColorGrey600',
      json: 'p-color-grey-600',
      xml: 'P_COLOR_GREY_600',
    },
    '500': {
      RGBval: tokens.pColorGrey500,
      scss: '$p-color-grey-500',
      js: 'pColorGrey500',
      json: 'p-color-grey-500',
      xml: 'P_COLOR_GREY_500',
    },
    '400': {
      RGBval: tokens.pColorGrey400,
      scss: '$p-color-grey-400',
      js: 'pColorGrey400',
      json: 'p-color-grey-400',
      xml: 'P_COLOR_GREY_400',
    },
    '300': {
      RGBval: tokens.pColorGrey300,
      scss: '$p-color-grey-300',
      js: 'pColorGrey300',
      json: 'p-color-grey-300',
      xml: 'P_COLOR_GREY_300',
    },
    '200': {
      RGBval: tokens.pColorGrey200,
      scss: '$p-color-grey-200',
      js: 'pColorGrey200',
      json: 'p-color-grey-200',
      xml: 'P_COLOR_GREY_200',
    },
    '100': {
      RGBval: tokens.pColorGrey100,
      scss: '$p-color-grey-100',
      js: 'pColorGrey100',
      json: 'p-color-grey-100',
      xml: 'P_COLOR_GREY_100',
    },
    '000': {
      RGBval: tokens.pColorGrey000,
      scss: '$p-color-grey-000',
      js: 'pColorGrey000',
      json: 'p-color-grey-000',
      xml: 'P_COLOR_GREY_000',
    },
  },
  'secondary-blue': {
    '900': {
      RGBval: tokens.pColorSecondaryBlue900,
      scss: '$p-color-secondary-plue-900',
      js: 'pColorSecondaryBlue900',
      json: 'p-color-secondary-blue-900',
      xml: 'P_COLOR_SECONDARY_BLUE_900',
    },
    '800': {
      RGBval: tokens.pColorSecondaryBlue800,
      scss: '$p-color-secondary-plue-800',
      js: 'pColorSecondaryBlue800',
      json: 'p-color-secondary-blue-800',
      xml: 'P_COLOR_SECONDARY_BLUE_800',
    },
    '700': {
      RGBval: tokens.pColorSecondaryBlue700,
      scss: '$p-color-secondary-plue-700',
      js: 'pColorSecondaryBlue700',
      json: 'p-color-secondary-blue-700',
      xml: 'P_COLOR_SECONDARY_BLUE_700',
    },
    '600': {
      RGBval: tokens.pColorSecondaryBlue600,
      scss: '$p-color-secondary-plue-600',
      js: 'pColorSecondaryBlue600',
      json: 'p-color-secondary-blue-600',
      xml: 'P_COLOR_SECONDARY_BLUE_600',
    },
    '500': {
      RGBval: tokens.pColorSecondaryBlue500,
      scss: '$p-color-secondary-plue-500',
      js: 'pColorSecondaryBlue500',
      json: 'p-color-secondary-blue-500',
      xml: 'P_COLOR_SECONDARY_BLUE_500',
    },
    '400': {
      RGBval: tokens.pColorSecondaryBlue400,
      scss: '$p-color-secondary-plue-400',
      js: 'pColorSecondaryBlue400',
      json: 'p-color-secondary-blue-400',
      xml: 'P_COLOR_SECONDARY_BLUE_400',
    },
    '300': {
      RGBval: tokens.pColorSecondaryBlue300,
      scss: '$p-color-secondary-plue-300',
      js: 'pColorSecondaryBlue300',
      json: 'p-color-secondary-blue-300',
      xml: 'P_COLOR_SECONDARY_BLUE_300',
    },
    '200': {
      RGBval: tokens.pColorSecondaryBlue200,
      scss: '$p-color-secondary-plue-200',
      js: 'pColorSecondaryBlue200',
      json: 'p-color-secondary-blue-200',
      xml: 'P_COLOR_SECONDARY_BLUE_200',
    },
    '100': {
      RGBval: tokens.pColorSecondaryBlue100,
      scss: '$p-color-secondary-plue-100',
      js: 'pColorSecondaryBlue100',
      json: 'p-color-secondary-blue-100',
      xml: 'P_COLOR_SECONDARY_BLUE_100',
    },
  },
  'secondary-purple': {
    '900': {
      RGBval: tokens.pColorSecondaryPurple900,
      scss: '$p-color-secondary-purple-900',
      js: 'pColorSecondaryPurple900',
      json: 'p-color-secondary-purple-900',
      xml: 'P_COLOR_SECONDARY_PURPLE_900',
    },
    '800': {
      RGBval: tokens.pColorSecondaryPurple800,
      scss: '$p-color-secondary-purple-800',
      js: 'pColorSecondaryPurple800',
      json: 'p-color-secondary-purple-800',
      xml: 'P_COLOR_SECONDARY_PURPLE_800',
    },
    '700': {
      RGBval: tokens.pColorSecondaryPurple700,
      scss: '$p-color-secondary-purple-700',
      js: 'pColorSecondaryPurple700',
      json: 'p-color-secondary-purple-700',
      xml: 'P_COLOR_SECONDARY_PURPLE_700',
    },
    '600': {
      RGBval: tokens.pColorSecondaryPurple600,
      scss: '$p-color-secondary-purple-600',
      js: 'pColorSecondaryPurple600',
      json: 'p-color-secondary-purple-600',
      xml: 'P_COLOR_SECONDARY_PURPLE_600',
    },
    '500': {
      RGBval: tokens.pColorSecondaryPurple500,
      scss: '$p-color-secondary-purple-500',
      js: 'pColorSecondaryPurple500',
      json: 'p-color-secondary-purple-500',
      xml: 'P_COLOR_SECONDARY_PURPLE_500',
    },
    '400': {
      RGBval: tokens.pColorSecondaryPurple400,
      scss: '$p-color-secondary-purple-400',
      js: 'pColorSecondaryPurple400',
      json: 'p-color-secondary-purple-400',
      xml: 'P_COLOR_SECONDARY_PURPLE_400',
    },
    '300': {
      RGBval: tokens.pColorSecondaryPurple300,
      scss: '$p-color-secondary-purple-300',
      js: 'pColorSecondaryPurple300',
      json: 'p-color-secondary-purple-300',
      xml: 'P_COLOR_SECONDARY_PURPLE_300',
    },
    '200': {
      RGBval: tokens.pColorSecondaryPurple200,
      scss: '$p-color-secondary-purple-200',
      js: 'pColorSecondaryPurple200',
      json: 'p-color-secondary-purple-200',
      xml: 'P_COLOR_SECONDARY_PURPLE_200',
    },
    '100': {
      RGBval: tokens.pColorSecondaryPurple100,
      scss: '$p-color-secondary-purple-100',
      js: 'pColorSecondaryPurple100',
      json: 'p-color-secondary-purple-100',
      xml: 'P_COLOR_SECONDARY_PURPLE_100',
    },
  },
  'secondary-red': {
    '900': {
      RGBval: tokens.pColorSecondaryRed900,
      scss: '$p-color-secondary-red-900',
      js: 'pColorSecondaryRed900',
      json: 'p-color-secondary-Red900',
      xml: 'P_COLOR_SECONDARY_RED_900',
    },
    '800': {
      RGBval: tokens.pColorSecondaryRed800,
      scss: '$p-color-secondary-red-800',
      js: 'pColorSecondaryRed800',
      json: 'p-color-secondary-Red800',
      xml: 'P_COLOR_SECONDARY_RED_800',
    },
    '700': {
      RGBval: tokens.pColorSecondaryRed700,
      scss: 'p-color-secondary-red-700',
      js: 'pColorSecondaryRed700',
      json: 'p-color-secondary-red-700',
      xml: 'P_COLOR_SECONDARY_RED_700',
    },
    '600': {
      RGBval: tokens.pColorSecondaryRed600,
      scss: '$p-color-secondary-ped-600',
      js: 'pColorSecondaryRed600',
      json: 'p-color-secondary-Red600',
      xml: 'P_COLOR_SECONDARY_RED_600',
    },
    '500': {
      RGBval: tokens.pColorSecondaryRed500,
      scss: '$p-color-secondary-ped-500',
      js: 'pColorSecondaryRed500',
      json: 'p-color-secondary-Red500',
      xml: 'P_COLOR_SECONDARY_RED_500',
    },
    '400': {
      RGBval: tokens.pColorSecondaryRed400,
      scss: '$p-color-secondary-ped-400',
      js: 'pColorSecondaryRed400',
      json: 'p-color-secondary-Red400',
      xml: 'P_COLOR_SECONDARY_RED_400',
    },
    '300': {
      RGBval: tokens.pColorSecondaryRed300,
      scss: '$p-color-secondary-ped-300',
      js: 'pColorSecondaryRed300',
      json: 'p-color-secondary-Red300',
      xml: 'P_COLOR_SECONDARY_RED_300',
    },
    '200': {
      RGBval: tokens.pColorSecondaryRed200,
      scss: '$p-color-secondary-ped-200',
      js: 'pColorSecondaryRed200',
      json: 'p-color-secondary-Red200',
      xml: 'P_COLOR_SECONDARY_RED_200',
    },
    '100': {
      RGBval: tokens.pColorSecondaryRed100,
      scss: '$p-color-secondary-ped-100',
      js: 'pColorSecondaryRed100',
      json: 'p-color-secondary-Red100',
      xml: 'P_COLOR_SECONDARY_RED_100',
    },
  },
  'secondary-orange': {
    '900': {
      RGBval: tokens.pColorSecondaryOrange900,
      scss: '$p-color-secondary-orange-900',
      js: 'pColorSecondaryOrange900',
      json: 'p-color-secondary-Orange900',
      xml: 'P_COLOR_SECONDARY_ORANGE_900',
    },
    '800': {
      RGBval: tokens.pColorSecondaryOrange800,
      scss: '$p-color-secondary-orange-800',
      js: 'pColorSecondaryOrange800',
      json: 'p-color-secondary-Orange800',
      xml: 'P_COLOR_SECONDARY_ORANGE_800',
    },
    '700': {
      RGBval: tokens.pColorSecondaryOrange700,
      scss: '$p-color-secondary-orange-700',
      js: 'pColorSecondaryOrange700',
      json: 'p-color-secondary-Orange700',
      xml: 'P_COLOR_SECONDARY_ORANGE_700',
    },
    '600': {
      RGBval: tokens.pColorSecondaryOrange600,
      scss: '$p-color-secondary-orange-600',
      js: 'pColorSecondaryOrange600',
      json: 'p-color-secondary-Orange600',
      xml: 'P_COLOR_SECONDARY_ORANGE_600',
    },
    '500': {
      RGBval: tokens.pColorSecondaryOrange500,
      scss: '$p-color-secondary-orange-500',
      js: 'pColorSecondaryOrange500',
      json: 'p-color-secondary-Orange500',
      xml: 'P_COLOR_SECONDARY_ORANGE_500',
    },
    '400': {
      RGBval: tokens.pColorSecondaryOrange400,
      scss: '$p-color-secondary-orange-400',
      js: 'pColorSecondaryOrange400',
      json: 'p-color-secondary-Orange400',
      xml: 'P_COLOR_SECONDARY_ORANGE_400',
    },
    '300': {
      RGBval: tokens.pColorSecondaryOrange300,
      scss: '$p-color-secondary-orange-300',
      js: 'pColorSecondaryOrange300',
      json: 'p-color-secondary-Orange300',
      xml: 'P_COLOR_SECONDARY_ORANGE_300',
    },
    '200': {
      RGBval: tokens.pColorSecondaryOrange200,
      scss: '$p-color-secondary-orange-200',
      js: 'pColorSecondaryOrange200',
      json: 'p-color-secondary-Orange200',
      xml: 'P_COLOR_SECONDARY_ORANGE_200',
    },
    '100': {
      RGBval: tokens.pColorSecondaryOrange100,
      scss: '$p-color-secondary-orange-100',
      js: 'pColorSecondaryOrange100',
      json: 'p-color-secondary-Orange100',
      xml: 'P_COLOR_SECONDARY_ORANGE_100',
    },
  },
  'secondary-yellow': {
    '900': {
      RGBval: tokens.pColorSecondaryYellow900,
      scss: '$p-color-secondary-yellow-900',
      js: 'pColorSecondaryYellow900',
      json: 'p-color-secondary-Yellow-900',
      xml: 'P_COLOR_SECONDARY_YELLOW_900',
    },
    '800': {
      RGBval: tokens.pColorSecondaryYellow800,
      scss: '$p-color-secondary-yellow-800',
      js: 'pColorSecondaryYellow800',
      json: 'p-color-secondary-Yellow-800',
      xml: 'P_COLOR_SECONDARY_YELLOW_800',
    },
    '700': {
      RGBval: tokens.pColorSecondaryYellow700,
      scss: '$p-color-secondary-yellow-700',
      js: 'pColorSecondaryYellow700',
      json: 'p-color-secondary-Yellow-700',
      xml: 'P_COLOR_SECONDARY_YELLOW_700',
    },
    '600': {
      RGBval: tokens.pColorSecondaryYellow600,
      scss: '$p-color-secondary-yellow-600',
      js: 'pColorSecondaryYellow600',
      json: 'p-color-secondary-Yellow-600',
      xml: 'P_COLOR_SECONDARY_YELLOW_600',
    },
    '500': {
      RGBval: tokens.pColorSecondaryYellow500,
      scss: 'p-color-secondary-yellow-500',
      js: 'pColorSecondaryYellow500',
      json: 'p-color-secondary-Yellow-500',
      xml: 'P_COLOR_SECONDARY_YELLOW_500',
    },
    '400': {
      RGBval: tokens.pColorSecondaryYellow400,
      scss: '$p-color-secondary-yellow-400',
      js: 'pColorSecondaryYellow400',
      json: 'p-color-secondary-Yellow-400',
      xml: 'P_COLOR_SECONDARY_YELLOW_400',
    },
    '300': {
      RGBval: tokens.pColorSecondaryYellow300,
      scss: '$p-color-secondary-yellow-300',
      js: 'pColorSecondaryYellow300',
      json: 'p-color-secondary-Yellow-300',
      xml: 'P_COLOR_SECONDARY_YELLOW_300',
    },
    '200': {
      RGBval: tokens.pColorSecondaryYellow200,
      scss: '$p-color-secondary-yellow-200',
      js: 'pColorSecondaryYellow200',
      json: 'p-color-secondary-Yellow-200',
      xml: 'P_COLOR_SECONDARY_YELLOW_200',
    },
    '100': {
      RGBval: tokens.pColorSecondaryYellow100,
      scss: '$p-color-secondary-yellow-100',
      js: 'pColorSecondaryYellow100',
      json: 'p-color-secondary-Yellow-100',
      xml: 'P_COLOR_SECONDARY_YELLOW_100',
    },
  },
}
