const fs = require('fs')
const { createComponentName } = require('./tools')

// icons: Array of icons SVG code
const generateIconComponents = (icons, iconsComponentsOutput) => {
  const fileHeader = `/*********************************************************************
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
**********************************************************************/
import React from 'react' 
`

  // parsing svg to add "fill" property
  const regexFill = /<path|<circle|<rect|<polygon|<polyline|<text|<textpath/g

  // Icons components file content
  let fileContent = icons.map(iconSVG => {
    const { fileName, data } = iconSVG

    // filtering file name to remove "--", ".svg", and any other invalid character for a component name
    const parsedFileName = createComponentName(fileName)
    const parsedData = data
      .replace('<svg', '<svg {...rest}')
      .replace(regexFill, '$& fill={fill}')
    const reactComponent = `export const ${parsedFileName} = ({fill,...rest}) => ${parsedData}`
    return reactComponent
  })

  fileContent.unshift(fileHeader)
  fileContent = fileContent.join('\n\n')
  return new Promise((res, rej) => {
    fs.writeFile(iconsComponentsOutput, fileContent, 'utf8', err => {
      if (err) {
        return rej(err)
      }
      res(true)
    })
  })
}

module.exports = generateIconComponents
