const { createComponentName, convertPxToRem } = require('./tools')

const fileHeader = `/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/

import React from 'react'`

const iconContent = ({ fileName, data, size }) => {
  const parsedData = data.replace(
    '<svg',
    '<svg width={size} height={size} {...rest} fill={fill}'
  )
  const parsedName = createComponentName(fileName)
  return `export const ${parsedName} = ({fill, size = '${convertPxToRem(
    size
  )}', ...rest}) => (${parsedData})`
}

const reactIconsIndex = iconList => `${fileHeader}

${iconList.map(iconContent).join(`

`)}`

module.exports.reactIconsIndex = reactIconsIndex
