const { createComponentName, convertPxToRem } = require('./tools')

const fileHeader = `/*
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
*/`

const vueIconComponent = ({ fileName, data, size }) => {
  const parsedFileName = createComponentName(fileName)
  const parsedData = data.replace(
    '<svg',
    '<svg height={this.size} width={this.size} fill={this.fill}'
  )
  return `
  export const ${parsedFileName} = {
    render() {
      return (
        ${parsedData}
      )
    },
    props: {
      size: {
        type: String,
        default: '${convertPxToRem(size)}'
      },
      fill: {
        type: String,
        required: true
      }
    }
  }
`
}

const vueIconsIndex = iconList => `<script>
${fileHeader}
${iconList.map(vueIconComponent).join('')}
</script>`

module.exports.vueIconsIndex = vueIconsIndex
