import React from 'react'
/*********************************************************************
DON'T EDIT THIS FILE
It was auto-generated by "iconCompiler" script
**********************************************************************/

const Navigation_Arrow_Arrow__Bottom_16px = ({ fill }) => {
  return <p>oioi {fill}</p>
}

module.exports = Navigation_Arrow_Arrow__Bottom_16px

// export const Navigation_Arrow_Arrow__Bottom_16px = ({fill}) => (<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill={fill} d="M8 11.5a1 1 0 01-.71-.29l-5-5a1 1 0 011.42-1.42L8 9.09l4.29-4.3a1 1 0 111.42 1.42l-5 5a1 1 0 01-.71.29z"/></svg>)
